### ISSUE TITLE
Looks good.

### ISSUE THREAD

**Issue by soggybag** [Nyapal/css-art#1]
That flower is positioning the center with absolute position and a % left. This is going to make it change position if the window changes size! The % left will be equal to a % of the width of the window. 

Better to use px here. 

Better yet, wrap all of the flower parts in a div container and make that `position: relative`. Now all absolutely positioned descendants will calculate their position from the edges of this container.

**Comment by Nyapal** [comment]
Refactored my code using flexbox and updated the class repo!
